coordinate_system: reference_image
crowd_sim:
  agent_groups:
    - {agents_name: [], agents_number: 0, group_id: 0, profile_selector: external_agent, state_selector: external_static, x: 0, y: 0}
  agent_profiles:
    - {ORCA_tau: 1, ORCA_tauObst: 0.40000000000000002, class: 1, max_accel: 0, max_angle_vel: 0, max_neighbors: 10, max_speed: 0, name: external_agent, neighbor_dist: 5, obstacle_set: 1, pref_speed: 0, r: 0.25}
  enable: 0
  goal_sets: []
  model_types: []
  obstacle_set: {class: 1, file_name: youtalk_navmesh.nav, type: nav_mesh}
  states:
    - {final: 1, goal_set: -1, name: external_static, navmesh_file_name: ""}
  transitions: []
  update_time_step: 0.10000000000000001
graphs:
  {}
levels:
  youtalk:
    drawing:
      filename: map.png
    elevation: 0
    floors:
      - parameters: {ceiling_scale: [3, 1], ceiling_texture: [1, blue_linoleum], indoor: [2, 0], texture_name: [1, blue_linoleum], texture_rotation: [3, 0], texture_scale: [3, 1]}
        vertices: [21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    lanes:
      - [46, 53, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [53, 45, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [53, 54, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [54, 48, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [54, 47, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [54, 55, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [55, 49, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [55, 56, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [56, 50, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [56, 51, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [56, 57, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [56, 58, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [58, 52, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 0], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
      - [49, 59, {bidirectional: [4, true], demo_mock_floor_name: [1, ""], demo_mock_lift_name: [1, ""], graph_idx: [2, 2], mutex: [1, ""], orientation: [1, ""], speed_limit: [3, 0]}]
    layers:
      {}
    measurements:
      - [41, 42, {distance: [3, 2.25]}]
      - [43, 44, {distance: [3, 2.7000000000000002]}]
    vertices:
      - [147.93199999999999, 229.739, 0, ""]
      - [242.54599999999999, 227.91, 0, ""]
      - [242.285, 167.535, 0, ""]
      - [320.69400000000002, 166.22800000000001, 0, ""]
      - [321.21699999999998, 138, 0, ""]
      - [243.59200000000001, 138.78399999999999, 0, ""]
      - [243.59200000000001, 109.773, 0, ""]
      - [306.31900000000002, 109.773, 0, ""]
      - [305.79599999999999, 82.852999999999994, 0, ""]
      - [279.92099999999999, 82.067999999999998, 0, ""]
      - [279.137, 47.045999999999999, 0, ""]
      - [353.62599999999998, 48.091000000000001, 0, ""]
      - [355.71699999999998, 108.205, 0, ""]
      - [470.71699999999998, 104.807, 0, ""]
      - [471.50099999999998, 134.60300000000001, 0, ""]
      - [355.97800000000001, 138.523, 0, ""]
      - [357.024, 224.251, 0, ""]
      - [471.24000000000001, 224.512, 0, ""]
      - [473.59199999999998, 302.137, 0, ""]
      - [358.06900000000002, 299.78500000000003, 0, ""]
      - [358.33100000000002, 350.22800000000001, 0, ""]
      - [148.97800000000001, 352.84199999999998, 0, ""]
      - [320.95499999999998, 82.590999999999994, 0, ""]
      - [246.989, 190.535, 0, ""]
      - [296.387, 190.273, 0, ""]
      - [296.387, 223.46700000000001, 0, ""]
      - [248.55799999999999, 223.989, 0, ""]
      - [250.126, 259.012, 0, ""]
      - [274.43299999999999, 258.48899999999998, 0, ""]
      - [275.21699999999998, 339.512, 0, ""]
      - [324.09199999999998, 346.56900000000002, 0, ""]
      - [341.34199999999998, 318.07999999999998, 0, ""]
      - [353.62599999999998, 326.44400000000002, 0, ""]
      - [241.501, 257.96699999999998, 0, ""]
      - [242.285, 347.35300000000001, 0, ""]
      - [152.114, 335.85300000000001, 0, ""]
      - [168.84100000000001, 335.32999999999998, 0, ""]
      - [168.31899999999999, 319.649, 0, ""]
      - [198.114, 318.86500000000001, 0, ""]
      - [197.85300000000001, 336.637, 0, ""]
      - [241.762, 336.11500000000001, 0, ""]
      - [366.17099999999999, 137.739, 0, ""]
      - [368.262, 225.29599999999999, 0, ""]
      - [357.54599999999999, 214.84200000000001, 0, ""]
      - [470.71699999999998, 214.31899999999999, 0, ""]
      - [309.71699999999998, 96.704999999999998, 0, Charger, {is_charger: [4, true]}]
      - [338.20499999999998, 62.726999999999997, 0, ""]
      - [420.01299999999998, 120.75, 0, Bath]
      - [277.30799999999999, 123.887, 0, Kitchen]
      - [307.10300000000001, 206.21600000000001, 0, Dining]
      - [289.06900000000002, 260.31900000000002, 0, Sofa]
      - [417.13799999999998, 231.30699999999999, 0, Closet]
      - [210.92099999999999, 322.78500000000003, 0, Desk]
      - [338.46699999999998, 96.704999999999998, 0, ""]
      - [338.72800000000001, 122.58, 0, ""]
      - [339.774, 205.17099999999999, 0, ""]
      - [339.512, 242.023, 0, ""]
      - [345.00099999999998, 295.60300000000001, 0, TV]
      - [227.387, 243.85300000000001, 0, ""]
      - [307.10300000000001, 241.762, 0, ""]
    walls:
      - [8, 22, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [23, 24, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [24, 25, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [25, 26, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [27, 28, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [28, 29, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [30, 31, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [31, 32, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [33, 34, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [35, 36, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [36, 37, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [37, 38, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [38, 39, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
      - [39, 40, {alpha: [3, 1], texture_height: [3, 2.5], texture_name: [1, default], texture_scale: [3, 1], texture_width: [3, 1]}]
lifts: {}
name: kachaka-youtalk
