#!/usr/bin/env python3

import sys

aio_base = open("python/kachaka_api/aio/base.py")
output_path = "python/kachaka_api/base.py"
if len(sys.argv) > 1:
    output_path = sys.argv[1]
output = open(output_path, "w")

output.write("# This file generated by tools/update_kachaka_api_base.py\n")
output.write("# Don't edit directly\n\n")
for line in aio_base:
    line = line.replace("await ", "")
    line = line.replace("async ", "")
    line = line.replace("from ..generated", "from .generated")
    line = line.replace("grpc.aio.", "grpc.")
    output.write(line)
